apiVersion: v1
kind: Pod
metadata:
 name: podtest2
spec:
  containers:
    - name: cont1
      image: nginx:alpine
      ports:
        - containerPort: 66
---
apiVersion: v1
kind: Pod
metadata:
 name: podtest3
spec:
  containers:
    - name: cont1
      image: nginx:alpine
      ports:
        - containerPort: 265